language: node_js
branches:
    only:
        - master
notifications:
    email: false
node_js:
    - node
script:
    - yarn build
after_success:
    - yarn report-coverage
    - yarn semantic-release
